### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by cpursley** [Wellers0n/react-admin-postgrest-client#4]
**Failed to compile**

```
./node_modules/react-admin-postgrest-client/src/authProvider.js

Module not found: Can't resolve 'jwt-decode' in 'admin/node_modules/react-admin-postgrest-client/src'
```

"react-admin": "^2.0.2"

I'm using the postgrest backend from this example: https://github.com/mattddowney/compose-postgrest

Any advice?

**Comment by Wellers0n** [comment]
`yarn add jwt-decode`
